-- Keep a durable, non-public decision audit and bound application submission
-- volume independently of the web process.
create table public.application_status_audit (
  id bigint generated by default as identity primary key,
  application_id bigint references public.applications(id) on delete set null,
  startup_id bigint not null,
  actor_id uuid,
  previous_status text not null,
  new_status text not null,
  changed_at timestamptz not null default now(),
  constraint application_status_audit_transition_check
    check (previous_status = 'pending' and new_status in ('accepted', 'rejected'))
);

alter table public.application_status_audit enable row level security;
revoke all on table public.application_status_audit from anon, authenticated;
revoke all on sequence public.application_status_audit_id_seq from anon, authenticated;
grant all privileges on table public.application_status_audit to service_role;
grant all privileges on sequence public.application_status_audit_id_seq to service_role;

create index applications_applicant_created_idx
  on public.applications (applicant_id, created_at desc);

create or replace function public.limit_application_submissions()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if (
    select count(*)
    from public.applications
    where applicant_id = new.applicant_id
      and created_at >= clock_timestamp() - interval '1 hour'
  ) >= 20 then
    raise exception using
      errcode = 'P0001',
      message = 'Application submission rate limit exceeded';
  end if;

  return new;
end;
$$;

create trigger applications_limit_submissions
  before insert on public.applications
  for each row execute procedure public.limit_application_submissions();

create or replace function public.audit_application_status_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.status is distinct from old.status then
    insert into public.application_status_audit (
      application_id,
      startup_id,
      actor_id,
      previous_status,
      new_status
    ) values (
      new.id,
      new.startup_id,
      auth.uid(),
      old.status,
      new.status
    );
  end if;

  return new;
end;
$$;

create trigger applications_audit_status_change
  after update of status on public.applications
  for each row execute procedure public.audit_application_status_change();
