-- Startup Zone domain schema.
create type public.user_role as enum ('founder', 'team_seeker', 'investor');

create table public.profiles (
  id uuid references auth.users on delete cascade primary key,
  role public.user_role not null default 'founder',
  full_name text,
  avatar_url text,
  bio text,
  location text,
  linkedin_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.startups (
  id bigint generated by default as identity primary key,
  founder_id uuid references public.profiles(id) on delete cascade not null,
  title text not null check (char_length(title) between 3 and 80),
  slug text unique not null check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  one_pager text not null check (char_length(one_pager) between 10 and 240),
  description text not null check (char_length(description) between 50 and 5000),
  stage text not null check (stage in ('idea', 'mvp', 'pre_seed', 'seed', 'series_a', 'later')),
  niche text[] not null default '{}',
  funding_ask numeric check (funding_ask is null or funding_ask > 0),
  equity_offered numeric check (equity_offered is null or equity_offered between 0 and 100),
  deck_url text,
  website_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.applications (
  id bigint generated by default as identity primary key,
  startup_id bigint references public.startups(id) on delete cascade not null,
  applicant_id uuid references public.profiles(id) on delete cascade not null,
  type text not null check (type in ('team', 'investor')),
  message text check (message is null or char_length(message) <= 2000),
  status text not null default 'pending' check (status in ('pending', 'accepted', 'rejected')),
  created_at timestamptz not null default now(),
  unique (startup_id, applicant_id, type)
);

create index startups_active_created_idx
  on public.startups (created_at desc)
  where is_active = true;

create index applications_startup_idx on public.applications (startup_id);
create index applications_applicant_idx on public.applications (applicant_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_set_updated_at
  before update on public.profiles
  for each row execute procedure public.set_updated_at();

create trigger startups_set_updated_at
  before update on public.startups
  for each row execute procedure public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, role, full_name)
  values (new.id, 'founder', new.raw_user_meta_data ->> 'full_name');
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.startups enable row level security;
alter table public.applications enable row level security;

create policy "Public profiles are readable" on public.profiles
  for select using (true);

create policy "Users can update their profile" on public.profiles
  for update using (auth.uid() = id)
  with check (auth.uid() = id);

create policy "Active startups are readable" on public.startups
  for select using (is_active or founder_id = auth.uid());

create policy "Founders can create startups" on public.startups
  for insert with check (founder_id = auth.uid());

create policy "Founders can update their startups" on public.startups
  for update using (founder_id = auth.uid())
  with check (founder_id = auth.uid());

create policy "Founders can delete their startups" on public.startups
  for delete using (founder_id = auth.uid());

create policy "Applicants can read their applications" on public.applications
  for select using (applicant_id = auth.uid());

create policy "Founders can read applications to their startups" on public.applications
  for select using (
    exists (
      select 1
      from public.startups
      where startups.id = applications.startup_id
        and startups.founder_id = auth.uid()
    )
  );

create policy "Users can create their applications" on public.applications
  for insert with check (applicant_id = auth.uid());

create policy "Founders can update application status" on public.applications
  for update using (
    exists (
      select 1
      from public.startups
      where startups.id = applications.startup_id
        and startups.founder_id = auth.uid()
    )
  );
