-- Treat stored external URLs as public-content boundaries. Application
-- validation provides field errors; these constraints remain authoritative for
-- direct Data API writes.

create or replace function public.external_url_hostname(value text)
returns text
language plpgsql
immutable
strict
security invoker
set search_path = ''
as $$
declare
  authority text;
begin
  if value !~ '^https://' then return null; end if;

  authority := substring(value from '^https://([^/?#]+)');
  if authority is null
    or authority like '%@%'
    or authority like '[%' then
    return null;
  end if;

  if authority ~ ':[0-9]+$' then
    if authority !~ ':443$' then return null; end if;
    authority := regexp_replace(authority, ':443$', '');
  end if;

  return lower(authority);
end;
$$;

create or replace function public.is_public_https_url(value text)
returns boolean
language plpgsql
immutable
strict
security invoker
set search_path = ''
as $$
declare
  hostname text := public.external_url_hostname(value);
begin
  return
    value = btrim(value)
    and char_length(value) <= 2048
    and value !~ '[[:space:]]'
    and hostname is not null
    and hostname ~ '^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?(\.[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?)+$'
    and hostname !~ '^[0-9.]+$'
    and hostname <> 'localhost'
    and hostname !~ '(\.localhost|\.local|\.internal|\.home\.arpa)$';
end;
$$;

create or replace function public.is_pitch_deck_url(value text)
returns boolean
language sql
immutable
strict
security invoker
set search_path = ''
as $$
  select
    public.is_public_https_url(value)
    and (
      value ~* '\.pdf([?#]|$)'
      or public.external_url_hostname(value) in (
        'docsend.com',
        'docs.google.com',
        'drive.google.com',
        'pitch.com',
        'www.docsend.com',
        'www.pitch.com'
      )
    );
$$;

revoke all on function public.external_url_hostname(text) from public;
revoke all on function public.is_public_https_url(text) from public;
revoke all on function public.is_pitch_deck_url(text) from public;

alter table public.startups
  drop constraint if exists startups_website_url_http_check,
  drop constraint if exists startups_deck_url_http_check,
  add constraint startups_website_url_http_check
    check (website_url is null or public.is_public_https_url(website_url)) not valid,
  add constraint startups_deck_url_http_check
    check (deck_url is null or public.is_pitch_deck_url(deck_url)) not valid;

alter table public.profiles
  drop constraint if exists profiles_avatar_url_http_check,
  drop constraint if exists profiles_linkedin_url_check,
  drop constraint if exists profiles_website_url_http_check,
  add constraint profiles_avatar_url_http_check
    check (avatar_url is null or public.is_public_https_url(avatar_url)) not valid,
  add constraint profiles_linkedin_url_check
    check (
      linkedin_url is null
      or (
        public.is_public_https_url(linkedin_url)
        and (
          public.external_url_hostname(linkedin_url) = 'linkedin.com'
          or public.external_url_hostname(linkedin_url) like '%.linkedin.com'
        )
      )
    ) not valid,
  add constraint profiles_website_url_http_check
    check (website_url is null or public.is_public_https_url(website_url)) not valid;

alter table public.profile_contacts
  drop constraint if exists profile_contacts_url_check,
  add constraint profile_contacts_url_check
    check (contact_url is null or public.is_public_https_url(contact_url)) not valid;

alter table public.startups validate constraint startups_website_url_http_check;
alter table public.startups validate constraint startups_deck_url_http_check;
alter table public.profiles validate constraint profiles_avatar_url_http_check;
alter table public.profiles validate constraint profiles_linkedin_url_check;
alter table public.profiles validate constraint profiles_website_url_http_check;
alter table public.profile_contacts validate constraint profile_contacts_url_check;

create table public.content_reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid references public.profiles(id) on delete set null,
  startup_id bigint references public.startups(id) on delete set null,
  link_kind text not null,
  reported_url text not null,
  reason text not null,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  constraint content_reports_link_kind_check
    check (link_kind in ('website', 'deck')),
  constraint content_reports_url_check
    check (public.is_public_https_url(reported_url)),
  constraint content_reports_reason_check
    check (reason in ('phishing', 'malware', 'misleading', 'privacy', 'other')),
  constraint content_reports_status_check
    check (status in ('pending', 'resolved', 'dismissed')),
  constraint content_reports_review_check
    check (
      (status = 'pending' and reviewed_at is null)
      or (status in ('resolved', 'dismissed') and reviewed_at is not null)
    )
);

create unique index content_reports_one_pending_report_idx
  on public.content_reports (reporter_id, startup_id, link_kind)
  where status = 'pending' and reporter_id is not null;

create index content_reports_pending_created_idx
  on public.content_reports (created_at)
  where status = 'pending';

alter table public.content_reports enable row level security;
revoke all on table public.content_reports from public, anon, authenticated;
revoke all on sequence public.content_reports_id_seq from public, anon, authenticated;
grant all privileges on table public.content_reports to service_role;
grant all privileges on sequence public.content_reports_id_seq to service_role;

create or replace function public.report_startup_link(
  reported_startup_id bigint,
  reported_link_kind text,
  reported_reason text
)
returns boolean
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  account_id uuid := auth.uid();
  current_url text;
begin
  if account_id is null then
    raise exception using errcode = '42501', message = 'Authentication required';
  end if;

  if reported_link_kind not in ('website', 'deck')
    or reported_reason not in ('phishing', 'malware', 'misleading', 'privacy', 'other') then
    raise exception using errcode = '22023', message = 'Invalid content report';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(account_id::text, 0));

  if (
    select count(*)
    from public.content_reports
    where reporter_id = account_id
      and created_at >= clock_timestamp() - interval '1 hour'
  ) >= 5 then
    raise exception using errcode = 'P0001', message = 'Content report rate limit exceeded';
  end if;

  select case reported_link_kind
    when 'website' then startups.website_url
    when 'deck' then startups.deck_url
  end
  into current_url
  from public.startups
  where startups.id = reported_startup_id
    and startups.is_active;

  if current_url is null then
    raise exception using errcode = '22023', message = 'Reported link is unavailable';
  end if;

  begin
    insert into public.content_reports (
      reporter_id,
      startup_id,
      link_kind,
      reported_url,
      reason
    ) values (
      account_id,
      reported_startup_id,
      reported_link_kind,
      current_url,
      reported_reason
    );
  exception when unique_violation then
    return false;
  end;

  return true;
end;
$$;

revoke all on function public.report_startup_link(bigint, text, text) from public, anon;
grant execute on function public.report_startup_link(bigint, text, text) to authenticated;

comment on table public.content_reports is
  'Operator-only moderation queue for user-reported public startup links.';
comment on function public.report_startup_link(bigint, text, text) is
  'Captures the current persisted link with duplicate and per-account rate limits.';
