-- Create enum for user roles
create type public.user_role as enum ('founder', 'team_seeker', 'investor');

-- Profiles table (основная таблица для всех пользователей)
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  role public.user_role not null default 'founder',
  full_name text,
  avatar_url text,
  bio text,
  location text,
  linkedin_url text,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

-- Startups table (то, что размещают founders)
create table if not exists public.startups (
  id bigint generated by default as identity primary key,
  founder_id uuid references public.profiles(id) on delete cascade not null,
  title text not null,
  slug text unique not null,
  one_pager text,
  description text,
  stage text check (stage in ('idea', 'mvp', 'pre_seed', 'seed', 'series_a', 'later')),
  niche text[] default '{}',                    -- массив ниш (AI, Fintech, Health и т.д.)
  funding_ask numeric,                          -- сумма, которую ищут
  equity_offered numeric,                       -- % equity
  deck_url text,                                -- ссылка на презентацию
  website_url text,
  is_active boolean default true,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

-- Applications table (заявки в команду или от инвесторов)
create table if not exists public.applications (
  id bigint generated by default as identity primary key,
  startup_id bigint references public.startups(id) on delete cascade not null,
  applicant_id uuid references public.profiles(id) on delete cascade not null,
  type text check (type in ('team', 'investor')) not null,   -- заявка в команду или инвестиционная
  message text,
  status text check (status in ('pending', 'accepted', 'rejected')) default 'pending',
  created_at timestamptz default now() not null
);

-- Enable RLS on all tables
alter table public.profiles enable row level security;
alter table public.startups enable row level security;
alter table public.applications enable row level security;

-- Function to automatically create profile after signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, role, full_name)
  values (
    new.id,
    'founder',                    -- по умолчанию founder (можно менять позже)
    new.raw_user_meta_data->>'full_name'
  );
  return new;
end;
$$ language plpgsql security definer;

-- Trigger for new user
create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Basic RLS policies (можно расширять позже)

-- Profiles: user sees only own profile
create policy "Users can view own profile" on public.profiles
  for select using (auth.uid() = id);

create policy "Users can update own profile" on public.profiles
  for update using (auth.uid() = id);

-- Startups: everyone can read active startups, only founder can edit own
create policy "Anyone can read active startups" on public.startups
  for select using (is_active = true);

create policy "Founders can manage own startups" on public.startups
  for all using (founder_id = auth.uid());

-- Applications
create policy "Users can see own applications" on public.applications
  for select using (applicant_id = auth.uid());

create policy "Founders can see applications to their startups" on public.applications
  for select using (
    exists (
      select 1 from public.startups 
      where startups.id = applications.startup_id 
      and startups.founder_id = auth.uid()
    )
  );

create policy "Users can create applications" on public.applications
  for insert with check (applicant_id = auth.uid());
